name = "my-woker"
main = "src/index.ts"
compatibility_date = "2025-06-07"

# Compatibility flags
compatibility_flags = ["global_fetch_strictly_public"]

# Serve static assets from ./public
[assets]
directory = "./public"

# Enable observability
[observability]
enabled = true

# Environment variables (⚠️ avoid committing sensitive data)
[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDFKWDFUS1BXS1daTUJYU1RTRlpRS0ZKRDAiLCJ0ZW5hbnRfaWQiOiIyMzMyZWJjZGIxN2RkZWI0MzgzMThmNTJlNWI5YTQzNWEyZmMyZWViYjRiODk0NjkzNzkzMjQyMzQ4ZDMxYzc1IiwiaW50ZXJuYWxfc2VjcmV0IjoiYmM3NzkyYzUtOGM3NS00MWExLWFmMmEtM2UyMjNiYTc4NDRmIn0.tvafmqUpudWtG_Co-03pxSUuCPX_cNkXA_67unykKg0"
